profit:
	@./tradelog profit stock-2.log
hist:
	@./tradelog hist-ord stock-2.log
graph:
	@./tradelog graph-pos stock-6.log
list:
	@./tradelog list-tick stock-2.log
pos:
	@./tradelog pos stock-6.log
last:
	@./tradelog last-price stock-2.log
sort:
	@./tradelog show-sort stock-6.log
graph-v:
	@./tradelog -w 100 graph-pos stock-6.log
